{% set name = "apache-airflow-core" %}
{% set version = "3.1.0" %}
{% set python_over = "3.14" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_core-{{ version }}.tar.gz
  sha256: d98f0c1c9226041e23098cd27c7f0b215e3b59984070d9c339aa7f34504107fd

build:
  number: 0
  noarch: python

outputs:
  - name: {{ name }}
    script: install_airflow_core.sh
    build:
      entry_points:
        - airflow = airflow.__main__:main
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - gitpython ==3.1.45
        - gitdb ==4.0.12
        - hatchling ==1.27.0
        - packaging ==25.0
        - pathspec ==0.12.1
        - pluggy ==1.6.0
        - smmap ==5.0.2
        - tomli ==2.2.1
        - trove-classifiers ==2025.9.11.17
        - pip
      run:
        - python >={{ python_min }},<{{ python_over }}
        - a2wsgi >=1.10.8
        - aiosqlite >=0.20.0
        - alembic >=1.13.1,<2.0
        - argcomplete >=1.10
        - asgiref >=2.3.0
        - attrs >=22.1.0,!=25.2.0
        - cadwyn >=5.2.1
        - colorlog >=6.8.2
        - cron-descriptor >=1.2.24
        - croniter >=2.0.2
        - cryptography >=41.0.0
        - deprecated >=1.2.13
        - dill >=0.2.2
        # conda-forge package includes fastapi[standard]
        - fastapi >=0.116.0
        - starlette >=0.45.0
        - httpx >=0.25.0
        # most restrictive to stay noarch: python
        - importlib-metadata >=7.0
        - itsdangerous >=2.0
        - jinja2 >=3.1.5
        - jsonschema >=4.19.1
        - lazy-object-proxy >=1.2.0
        - libcst >=1.8.2
        - linkify-it-py >=2.0.0
        - lockfile >=0.12.2
        - methodtools >=0.4.7
        - opentelemetry-api >=1.27.0
        - opentelemetry-exporter-otlp >=1.27.0
        # leaving out opentelemetry-proto as this seems to be present 
        # for a pip issue that shouldn't apply to conda
        - packaging >=25.0
        - pathspec >=0.9.0
        # stricter constraint for py>=312 to stay noarch: python
        - pendulum >=3.1.0
        - pluggy >=1.5.0
        - psutil >=5.8.0
        - pydantic >=2.11.0
        - pygments >=2.0.1,!=2.19.0
        - pyjwt >=2.10.0
        - python-daemon >=3.0.0
        - python-dateutil >=2.7.0
        - python-slugify >=5.0
        - requests >=2.32.0,<3
        - rich-argparse >=1.0.0
        - rich >=13.6.0
        - setproctitle >=1.3.3
        - sqlalchemy >=1.4.49

        # sqlalchemy[asyncio]
        - greenlet !=0.4.17

        - sqlalchemy-jsonfield >=1.0
        - sqlalchemy-utils >=0.41.2
        - svcs >=25.1.0
        - tabulate >=0.9.0
        - tenacity >=8.3.0
        - termcolor >=3.0.0
        - typing-extensions >=4.14.1
        - universal-pathlib >=0.2.2,!=0.2.4
        - uuid6 >=2024.7.10
        - apache-airflow-task-sdk <1.2.0,>=1.1.0
        - apache-airflow-providers-common-compat >=1.6.0
        - apache-airflow-providers-common-io >=1.5.3
        - apache-airflow-providers-common-sql >=1.26.0
        - apache-airflow-providers-smtp >=2.0.2
        - apache-airflow-providers-standard >=0.4.0
        - msgspec >=0.19.0
        - pygtrie >=2.5.0
        - structlog >=25.4.0

    test:
      imports:
        - airflow
      commands:
        - pip check
        - airflow --help
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-async
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<{{ python_over }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - eventlet >=0.37.0
        - gevent >=25.4.1
        - greenlet >=3.1.0
        - greenback >=1.2.1

    test:
      imports:
        - airflow
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-graphviz
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<{{ python_over }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - python-graphviz >=0.20

    test:
      imports:
        - airflow
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-kerberos
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<{{ python_over }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - pykerberos >=1.1.13
        - requests-kerberos >=0.14.0
        - thrift_sasl >=0.4.2

    test:
      imports:
        - airflow
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-otel
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<{{ python_over }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        # going with more recent versions because of incorrect deps in older versions
        - opentelemetry-exporter-prometheus >=0.51b0

    test:
      imports:
        - airflow
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-sentry
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<{{ python_over }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - blinker >=1.1
        - sentry-sdk >=2.30.0
        # sentry-sdk[flask] extra
        - flask >=0.11
        - blinker >=1.1
        - markupsafe

    test:
      imports:
        - airflow
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-statsd
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<{{ python_over }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - statsd >=3.3.0

    test:
      imports:
        - airflow
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-all
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<{{ python_over }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - {{ name }}-with-graphviz
        - {{ name }}-with-kerberos
        - {{ name }}-with-otel
        - {{ name }}-with-sentry
        - {{ name }}-with-statsd

    test:
      imports:
        - airflow
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

about:
  home: http://airflow.apache.org
  summary: Core packages for Apache Airflow, schedule and API server
  license: MIT AND BSD-3-Clause AND BSD-2-Clause AND Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
    - 3rd-party-licenses/LICENSE-reproducible.txt
    - 3rd-party-licenses/LICENSE-dagre-d3.txt
    - 3rd-party-licenses/LICENSE-elasticmock.txt
    - 3rd-party-licenses/LICENSE-eonasdan-bootstrap-datetimepicker.txt
    - 3rd-party-licenses/LICENSE-flask-kerberos.txt
    - 3rd-party-licenses/LICENSE-d3-shape.txt
    - 3rd-party-licenses/LICENSE-pytest-capture-warnings.txt
    - 3rd-party-licenses/LICENSE-bootstrap3-typeahead.txt
    - 3rd-party-licenses/LICENSE-datatables.txt
    - 3rd-party-licenses/LICENSE-hue.txt
    - 3rd-party-licenses/LICENSE-d3js.txt
    - 3rd-party-licenses/LICENSE-jqclock.txt
    - 3rd-party-licenses/LICENSE-moment.txt
    - 3rd-party-licenses/LICENSE-d3-tip.txt
    - 3rd-party-licenses/LICENSE-bootstrap.txt
    - 3rd-party-licenses/LICENSE-jquery.txt
    - 3rd-party-licenses/LICENSE-normalize.txt
  doc_url: http://pythonhosted.org/airflow/profiling.html
  dev_url: https://github.com/apache/airflow

extra:
  recipe-maintainers:
    - xylar
